Resume
front-end-by-rimantas/19-grupe-portfolio-cristino pull request #40
Opened 2020-12-17 15:12 UTC by Gurar

2020-12-17 21:56 UTC, SarunasCeponis requested changes
nesicentruoja title img ir text?

2020-12-17 21:56 UTC, SarunasCeponis commented on css/home-page.css
> +    margin: 0 0 30px 0;
text-align center?

2020-12-17 21:57 UTC, SarunasCeponis commented on css/home-page.css
> +    margin: 0 0 30px 0;
ir bent jau pas mane nerodo img, nezinau kaip pas kitus

2020-12-18 09:35 UTC, Gurar commented on css/home-page.css
> +    margin: 0 0 30px 0;
as nedejau style nes kaskaz sake kad jau yra sukurtas componnentas section-title

2020-12-18 10:22 UTC, SarunasCeponis approved these changes

2020-12-18 12:01 UTC, 7traders approved these changes

2020-12-18 12:03 UTC, merged